version: "3.9"

services:
  prometheus:
    image: prom/prometheus:v2.54.1
    container_name: monitoring-prometheus
    restart: unless-stopped
    user: "${RUN_UID}:${RUN_GID}"
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.enable-lifecycle"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./data/prometheus:/prometheus:Z
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - monitoring
    depends_on:
      - pushgateway

  pushgateway:
    image: prom/pushgateway:latest
    container_name: monitoring-pushgateway
    restart: unless-stopped
    ports:
      - "9091:9091"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:11.1.4
    container_name: monitoring-grafana
    restart: unless-stopped
    user: "472:472"
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    volumes:
      - ./data/grafana:/var/lib/grafana:Z
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboard:/var/lib/grafana/dashboards:ro
    depends_on:
      - prometheus
    networks:
      - monitoring

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: monitoring-postgres-exporter
    restart: unless-stopped
    environment:
      DATA_SOURCE_NAME: "postgresql://app:app1234@host.docker.internal:5433/app?sslmode=disable"
    ports:
      - "9187:9187"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - monitoring

  elasticsearch-exporter:
    image: quay.io/prometheuscommunity/elasticsearch-exporter:latest
    container_name: monitoring-elasticsearch-exporter
    restart: unless-stopped
    command:
      - "--es.uri=http://host.docker.internal:9200"
      - "--es.all"
      - "--es.indices"
      - "--es.indices_settings"
      - "--es.shards"
    ports:
      - "9114:9114"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - monitoring
networks:
  monitoring:
    name: monitoring-net