global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "pushgateway"
    honor_labels: true
    static_configs:
      - targets: ["pushgateway:9091"]

  - job_name: "spring-api"
    static_configs:
      - targets: [ "host.docker.internal:80" ]
    metrics_path: /actuator/core/prometheus

  - job_name: "websocket-server"
    static_configs:
      - targets: [ "host.docker.internal:80" ]
    metrics_path: /actuator/ws/prometheus

  - job_name: "postgres"
    static_configs:
      - targets: [ "postgres-exporter:9187" ]

  - job_name: "elasticsearch"
    static_configs:
      - targets: [ "elasticsearch-exporter:9114" ]
