version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/monitoring
file_exists_behavior: OVERWRITE

permissions:
  - object: /
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: scripts/starts.sh
      timeout: 120
      runas: ubuntu
